### ISSUE TITLE
Questions: Can this be used with any other S3 Protocol?

### ISSUE THREAD

**Issue by JaysonBH** [spring-cloud-stream-app-starters/aws-s3#5]
Questions: Can this be used with any other S3 Protocol outside of Amazon AWS or is it tightly coupled with being used specifically with Amazon AWS S3?

Thanks

**Comment by artembilan** [comment]
I'm not aware of "any other S3 Protocol". Maximum what I can say that this project is fully tied with the [Spring Integration AWS](https://github.com/spring-projects/spring-integration-aws) and use an `AmazonS3` API to interact with the S3 protocol. So, if you know how to configure `AmazonS3` instance "outside of Amazon AWS", then this project can be used for whatever goal you are aimed.
See https://github.com/spring-cloud-stream-app-starters/aws-s3/blob/master/aws-s3-app-starters-common/src/main/java/org/springframework/cloud/stream/app/s3/AmazonS3Configuration.java for the particular `AmazonS3` instance configuration.

I'm closing this because you got an answer to your question even if it doesn't fit your requirements.
